### ISSUE TITLE
Prototipo

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-equipo-metztli#1]
[Prototipo Metztli.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-equipo-metztli/files/10862036/Prototipo.Metztli.pdf)

**Comment by Rmz-Rigo** [comment]
Calificacion: 20/20

**Comment by josealfredo79** [comment]
Bien hecho...
